# Generated by Django 5.2.7 on 2026-06-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parentchild',
            new_name='genealogy_p_child_i_b12095_idx',
            old_name='genealogy_p_child_i_78b4b2_idx',
        ),
        migrations.RenameIndex(
            model_name='parentchild',
            new_name='genealogy_p_marriag_880810_idx',
            old_name='genealogy_p_marriag_e095a7_idx',
        ),
        migrations.RenameIndex(
            model_name='parentchild',
            new_name='genealogy_p_parent__262a6e_idx',
            old_name='genealogy_p_parent__08cf55_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='genealogy_p_last_na_eef29a_idx',
            old_name='genealogy_p_last_na_5c5aca_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='genealogy_p_birth_d_c5547a_idx',
            old_name='genealogy_p_birth_d_7e10d8_idx',
        ),
    ]
